import type { Metadata } from "next";
import "@/styles/globals.css";
import SiteHeader from "@/components/header";
import SiteFooter from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth selection:bg-accent-500 selection:text-white no-touchevents hydrated"
      suppressHydrationWarning
    >
      <body className={`font-sans bg-white flex flex-col min-h-svh`}>
        <SiteHeader />
        <main className="grow">{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
